create table if not exists usuario (
                         id bigint not null,
                         pass varchar(255),
                         usr varchar(255),
                         primary key (id)
);

create table if not exists user_role (
                           id bigint generated by default as identity,
                           name enum ('ROLE_ADMIN','ROLE_USER'),
                           primary key (id)
);

create table if not exists users_roles (
                             role_id bigint not null unique,
                             user_id bigint not null
);

INSERT INTO USUARIO VALUES (1, '$2a$12$ed0rmMvC.e8958VMdVTp9./E5dXkvvnL6UDT.vihW8HLqX5ZGy0xm', 'admin');
INSERT INTO USUARIO VALUES (2, '$2a$12$iFTc/zvDzWT6PGFlB6FVxeoNuRRZPS9KEZF0ODuA1fZqWscGTgGX.', 'padrao');

INSERT INTO USER_ROLE VALUES (1,  'ROLE_ADMIN');
INSERT INTO USER_ROLE VALUES (2,  'ROLE_USER');

INSERT INTO USERS_ROLES VALUES (1,  1);
INSERT INTO USERS_ROLES VALUES (2,  2);